import type { Judge } from '@/lib/types';

export const JUDGES: Judge[] = [
  {
    id: 'vc-chad',
    name: 'VC Chad',
    personality: 'VC Chad',
    avatar: 'VcChadIcon',
    modelPath: '/models/vcfounder.glb',
    rarity: 'common',
    description: "Your idea burns cash faster than FTX.",
    voice: { name: 'Vex' },
  },
  {
    id: 'philosopher-ai',
    name: 'Philosopher AI',
    personality: 'Philosopher AI',
    avatar: 'PhilosopherAiIcon',
    modelPath: '/models/philosopher.glb',
    rarity: 'common',
    description: "But what is a startup, if not a soul yearning for Series A?",
    voice: { name: 'Pallas' },
  },
  {
    id: 'trollbot69',
    name: 'TrollBot69',
    personality: 'TrollBot69',
    avatar: 'TrollBot69Icon',
    modelPath: '/models/clown.glb',
    rarity: 'common',
    description: "Congrats! You just invented disappointment… again.",
    voice: { name: 'Echo' },
  },
    {
    id: 'cosmic-coder',
    name: 'Cosmic Coder',
    personality: 'Cosmic Coder',
    avatar: 'CosmicCoderIcon',
    modelPath: '/models/girl.glb',
    rarity: 'common',
    description: 'Your entire business logic is a single, unoptimized for-loop in the grand simulation.',
    voice: { name: 'Sirius' },
  },
  {
    id: 'modern-dadu',
    name: 'Modern Dadu',
    personality: 'Modern Dadu',
    avatar: 'ModernDaduIcon',
    modelPath: '/models/oldMan.glb',
    rarity: 'rare',
    description: "In my time, we called it jugaad, not innovation!",
    voice: { name: 'Enceladus' },
  },
  {
    id: 'outdated-genz',
    name: 'Outdated GenZ',
    personality: 'Outdated GenZ',
    avatar: 'OutdatedGenzIcon',
    modelPath: '/models/genz.glb',
    rarity: 'rare',
    description: "This pitch… mid. Needs more sigma energy.",
    voice: { name: 'Comet' },
  },
  {
    id: 'hype-beast',
    name: 'Hype Beast',
    personality: 'Hype Beast',
    avatar: 'HypeBeastIcon',
    modelPath: '/models/genz.glb',
    modelVariation: {
      scale: 1.2,
      rotation: [0, Math.PI, 0],
      color: '#ff6b6b',
    },
    rarity: 'rare',
    description: 'Is this even on StockX? Your idea has zero drip, fam.',
    voice: { name: 'Horus' },
  },
  {
    id: 'broken-judge',
    name: 'Broken Judge',
    personality: 'Broken Judge',
    avatar: 'BrokenJudgeIcon',
    modelPath: '/models/glitched.glb',
    rarity: 'glitch',
    description: "Error: Sanity not found. Recalibrating reality...",
    voice: { name: 'Algenib' },
  },
];
